# Generated by scripts/generate_bindings.py; DO NOT EDIT.
from __future__ import annotations

import calendar
import re
from typing import Annotated, Any, Literal, Self

from pydantic import AfterValidator, BaseModel, ConfigDict, Field, StrictStr, field_validator, model_validator


class TransportModel(BaseModel):
    model_config = ConfigDict(extra="forbid", strict=True)


_RFC3339_DATE_TIME = re.compile(
    r"^(?P<year>\d{4})-(?P<month>0[1-9]|1[0-2])-(?P<day>\d{2})"
    r"T(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d+)?"
    r"(?:Z|[+-](?:[01]\d|2[0-3]):[0-5]\d)$",
    re.ASCII | re.IGNORECASE,
)
_PLACEHOLDER_SCOPE_VALUES = frozenset(
    {
        "default", "environment_default", "global", "n/a", "na", "none", "null",
        "org_default", "organization_default", "placeholder", "project",
        "project_default", "tenant_default", "unknown", "unscoped",
    }
)
_MUTABLE_PIN_VALUES = frozenset({"current", "default", "head", "latest", "mutable"})
_TIMESTAMP_PIN = re.compile(
    r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:\d{2})$",
    re.IGNORECASE,
)


def _validate_date_time(value: str) -> str:
    match = _RFC3339_DATE_TIME.fullmatch(value)
    if match is None:
        raise ValueError("must be an RFC 3339 date-time string")
    year, month, day = (
        int(match[name]) for name in ("year", "month", "day")
    )
    if year == 0 or not 1 <= day <= calendar.monthrange(year, month)[1]:
        raise ValueError("must be an RFC 3339 date-time string")
    return value


def _validate_pin(value: str) -> str:
    if value.lower() in _MUTABLE_PIN_VALUES:
        raise ValueError("must identify an immutable state")
    if _TIMESTAMP_PIN.fullmatch(value):
        raise ValueError("must not be synthesized from a timestamp")
    return value


DateTimeString = Annotated[StrictStr, AfterValidator(_validate_date_time)]
IdentityString = Annotated[
    StrictStr,
    Field(pattern=r"^[A-Za-z0-9][A-Za-z0-9._:-]*$", max_length=256),
]
ImmutablePin = Annotated[
    StrictStr,
    Field(pattern=r"^[A-Za-z0-9][A-Za-z0-9._:+-]*$", max_length=256),
    AfterValidator(_validate_pin),
]


class WorkflowRefAlignment(TransportModel):
    ref_id: StrictStr = Field(pattern=r"^workflow:[A-Za-z0-9][A-Za-z0-9._:-]*$")
    ref_type: Literal["workflow"]
    source_capability: Literal["workflow_context"]
    organization_id: IdentityString
    environment_id: IdentityString
    workflow_id: IdentityString
    snapshot_id: ImmutablePin | None = None
    version: ImmutablePin | None = None

    @model_validator(mode="before")
    @classmethod
    def reject_explicit_null_pins(cls, value: Any) -> Any:
        if type(value) is dict and any(value.get(field, ...) is None for field in ("snapshot_id", "version")):
            raise ValueError("optional immutable pins must be omitted rather than null")
        return value

    @model_validator(mode="after")
    def validate_immutable_identity(self) -> Self:
        if self.snapshot_id is None and self.version is None:
            raise ValueError("snapshot_id or version is required")
        if self.ref_id != f"workflow:{self.workflow_id}":
            raise ValueError("ref_id must identify workflow_id")
        return self


FailureType = Literal[
    "hallucination",
    "tool_misuse",
    "scope_creep",
    "safety_boundary_violation",
    "performance_degradation",
    "context_loss",
    "confidence_miscalibration",
    "instruction_drift",
    "error_handling_failure",
    "integration_failure",
    "adversarial_vulnerability",
    "other",
]
Severity = Literal["cosmetic", "functional", "safety-critical"]


class IncidentRef(TransportModel):
    ref_id: StrictStr = Field(pattern=r"^incident:[A-Za-z0-9][A-Za-z0-9._:-]*$")
    ref_type: Literal["incident"]
    source_capability: Literal["forge"]
    organization_id: IdentityString
    environment_id: IdentityString
    external_uri: StrictStr = Field(min_length=1, max_length=2048)
    snapshot_id: ImmutablePin | None = None
    version: ImmutablePin | None = None
    created_at: DateTimeString
    summary: StrictStr = Field(min_length=1, max_length=500)
    incident_id: IdentityString
    failure_type: FailureType
    severity: Severity
    workflow_ref: WorkflowRefAlignment

    @field_validator("organization_id", "environment_id")
    @classmethod
    def reject_placeholder_scope(cls, value: str) -> str:
        if value.lower() in _PLACEHOLDER_SCOPE_VALUES:
            raise ValueError("scope must be explicit and non-placeholder")
        return value

    @model_validator(mode="before")
    @classmethod
    def reject_explicit_null_pins(cls, value: Any) -> Any:
        if type(value) is dict and any(value.get(field, ...) is None for field in ("snapshot_id", "version")):
            raise ValueError("optional immutable pins must be omitted rather than null")
        return value

    @model_validator(mode="after")
    def validate_semantic_invariants(self) -> Self:
        if self.snapshot_id is None and self.version is None:
            raise ValueError("snapshot_id or version is required")
        if self.ref_id != f"incident:{self.incident_id}":
            raise ValueError("ref_id must identify incident_id")
        for field in ("organization_id", "environment_id"):
            if getattr(self.workflow_ref, field) != getattr(self, field):
                raise ValueError(f"workflow_ref.{field} must equal ref.{field}")
        return self


class IncidentRefEnvelope(TransportModel):
    contract_version: Literal["proofhouse-shared-contracts/v0.1"]
    contract_name: Literal["IncidentRef"]
    producer_capability: Literal["forge"]
    producer_system: Literal["proofhouse-forge"]
    canonical_owner: Literal["forge"]
    issued_at: DateTimeString
    cache_policy: Literal["summary_snapshot"]
    ref: IncidentRef
